---
# defaults file for lynis

lynis_version: 2.3.2
lynis_version_sha256sum: ccc77cc66c14526824fd39dfb2539bb601249e9b70c87d1d0f2f917e23db0975

lynis_src_directory: /usr/local/src

lynis_dest_directory: /opt

lynis_log_directory: /var/log/lynis

lynis_cron: yes
lynis_cron_hour: 3
lynis_cron_minute: 30
